[profile.default]
slow-timeout = { period = "60s", terminate-after = 2, , grace-period = "30s" }

[test-groups]
serial-integration = { max-threads = 1 }

[[profile.default.overrides]]
filter = 'test(test::bottomless)'
test-group = 'serial-integration'
