[package]
name = "libsql_core"
version = "0.0.0"
edition = "2021"

[dependencies]
futures = "0.3.28"
libsql-sys = "0.1.1"
thiserror = "1.0.40"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports", "async", "async_futures"] }
pprof = { version = "0.11.1", features = ["criterion", "flamegraph"] }

[[bench]]
name = "benchmark"
harness = false
