[package]
name = "libsql-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3.64"
libsql = { path = "../../core", default_features = false }
wasm-bindgen = "0.2"
