[workspace]
resolver = "2"
members = [
  "core",
  "bindings/c",
  "bindings/js",
  "bindings/python",
  "replication",
  "libsql-sys",
  "libsql-shell",
  "wasmtime-bindings",
]

[profile.release]
codegen-units = 1
panic = "abort"
